Fixed crash in UiListener when launching activity with screen off.
When launching MainActivity with the screen off (e.g. from Android Studio) the application would crash due to:

java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState

Also use FragmentPagerAdapter in MainPagerAdapter as the number of tabs is small and can be stored in memory.

Test: manual
PiperOrigin-RevId: 179734952
Change-Id: Ib2ca9674f3174493da55bbbf0ef4053fcf73ab47