Update patch set 2
Patch Set 2: Code-Review-1

Seems to cause a dialer crash as follows

12-06 11:18:00.997  19791-19811/com.android.incallui E/AndroidRuntime? FATAL EXCEPTION: ReverseLookup
    Process: com.android.incallui, PID: 19791
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.android.dialer.calllog.ContactInfo.equals(java.lang.Object)' on a null object reference
            at com.android.dialer.lookup.ReverseLookupService.doLookup(ReverseLookupService.java:136)
            at com.android.dialer.lookup.ReverseLookupService.handleMessage(ReverseLookupService.java:87)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)

Patch-set: 2