Update patch set 1
Patch Set 1:

Danny - Here's the diff from your lineage-15.0 patch: https://gist.github.com/invisiblek/8e70efc42ce7334c3b6495d6cda49c50

But I must be going insane, I can't get this to compile because of:

packages/apps/Dialer/java/com/android/dialer/lookup/LookupProvider.java:320: error: cannot find symbol
            return locationManager.getLastLocation();
                                  ^
  symbol:   method getLastLocation()
  location: variable locationManager of type LocationManager
1 error

Although LocationManager in framework still has a getLastLocation() method, its still public, I see no reason it should be missing.

Patch-set: 1